"""
This module implements some bundles of tp, tn solutions for scores
"""

from ._tptn_solutions import (mcc_tp,
                                mcc_tn,
                                acc_tp,
                                acc_tn,
                                sens_tp,
                                spec_tn,
                                ppv_tp,
                                ppv_tn,
                                npv_tp,
                                npv_tn,
                                fbp_tp,
                                fbp_tn,
                                f1p_tp,
                                f1p_tn,
                                fbm_tp,
                                fbm_tn,
                                f1m_tp,
                                f1m_tn,
                                upm_tp,
                                upm_tn,
                                gm_tp,
                                gm_tn,
                                fm_tp,
                                fm_tn,
                                mk_tp,
                                mk_tn,
                                lrp_tp,
                                lrp_tn,
                                lrn_tp,
                                lrn_tn,
                                bm_tp,
                                bm_tn,
                                pt_tp,
                                pt_tn,
                                dor_tp,
                                dor_tn,
                                ji_tp,
                                ji_tn,
                                bacc_tp,
                                bacc_tn,
                                kappa_tp,
                                kappa_tn,
                                p4_tp,
                                p4_tn)

__all__ = ['tp_solutions', 'tn_solutions', 'tptn_solutions']

tp_solutions = {'mcc': mcc_tp,
                'acc': acc_tp,
                'sens': sens_tp,
                'ppv': ppv_tp,
                'npv': npv_tp,
                'fbp': fbp_tp,
                'f1p': f1p_tp,
                'fbm': fbm_tp,
                'f1m': f1m_tp,
                'upm': upm_tp,
                'gm': gm_tp,
                'fm': fm_tp,
                'mk': mk_tp,
                'lrp': lrp_tp,
                'lrn': lrn_tp,
                'bm': bm_tp,
                'pt': pt_tp,
                'dor': dor_tp,
                'ji': ji_tp,
                'bacc': bacc_tp,
                'kappa': kappa_tp,
                'p4': p4_tp}

tn_solutions = {'mcc': mcc_tn,
                'acc': acc_tn,
                'spec': spec_tn,
                'ppv': ppv_tn,
                'npv': npv_tn,
                'fbp': fbp_tn,
                'f1p': f1p_tn,
                'fbm': fbm_tn,
                'f1m': f1m_tn,
                'upm': upm_tn,
                'gm': gm_tn,
                'fm': fm_tn,
                'mk': mk_tn,
                'lrp': lrp_tn,
                'lrn': lrn_tn,
                'bm': bm_tn,
                'pt': pt_tn,
                'dor': dor_tn,
                'ji': ji_tn,
                'bacc': bacc_tn,
                'kappa': kappa_tn,
                'p4': p4_tn}

tptn_solutions = {key: {'tp': tp_solutions.get(key),
                        'tn': tn_solutions.get(key)} for key in tp_solutions}
