name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mlscorecheck/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mlscorecheck/**'

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/requirements.txt

      - name: Install package
        run: pip install -e .

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Check for warnings
        run: |
          cd docs
          make html 2>&1 | tee build.log
          if grep -q "WARNING\|ERROR" build.log; then
            echo "Documentation build contains warnings or errors"
            exit 1
          fi
          echo "Documentation built successfully without warnings"

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: documentation
          path: docs/_build/html/
          retention-days: 30
